# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗

# format = """
# $directory $fill $git_branch $cmd_duration
#  $character"""
format = """
$cmd_duration 󰜥 $directory $git_branch
$character"""

[fill]
symbol = '-'
style = 'fg:245'

[fill]
symbol = '-'
style = 'fg:245'

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[ ](bold fg:255)"
error_symbol = "[ ](bold fg:249)"

# Disable the package module, hiding it from the prompt completely

[git_branch]
style = "bg: 252"
symbol = "󰘬"
truncation_symbol = ""
format = " 󰜥 [](bold fg:252)[$symbol $branch(:$remote_branch)](fg:235 bg:252)[ ](bold fg:252)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '($state( $progress_current of $progress_total))($style)'
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 󱡷 "
untracked = " 󰎔 "
stashed = " 󰆓 "
modified = "  "
staged = '[++\($count\)](green)'
renamed = "  "
deleted = " 🗑 "

[hostname]
ssh_only = false
format =  "[•$hostname](bg:252 bold fg:235)[](bold fg:252)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = true

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:252 fg:235"
style_root = "red bold"
format = "[](bold fg:252)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " "
read_only = "  "
style = "bg:255 fg:black"
truncation_length = 2
truncation_symbol = ".../"
format = '[](bold fg:255)[󰉋 → $path]($style)[](bold fg:255)'


[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:252)[󰪢 $duration](bold bg:252 fg:235)[](bold fg:252)'

[bun]
format = 'via [🍔 $version](bold green) '

[c]
symbol = " "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = " "

[daml]
symbol = "daml "

[dart]
symbol = "  "

[deno]
symbol = " "

[dotnet]
symbol = "󰪮  "


[docker_context]
symbol = "  "

[elixir]
symbol = "  "

[elm]
symbol = "elm "


[golang]
symbol = " 󰟓 "

[guix_shell]
symbol = "  "

[hg_branch]
symbol = "hg "

[java]
symbol = "  "

[julia]
symbol = "  "

[kotlin]
symbol = " 󱈙 "

[lua]
symbol = "  "

[nodejs]
symbol = "󰎙 "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "  "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = " 󰣇 "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = " 󰏗 "

[perl]
symbol = "  "

[php]
symbol = "  "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "  "

[raku]
symbol = "raku "

[ruby]
symbol = "  "

[rust]
symbol = " 󱘗 "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = " "

[terraform]
symbol = "terraform "

[zig]
symbol = "  "


[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '

[[battery.display]]
threshold = 30
style = 'bold red'

[buf]
symbol = '🦬 '

[custom.react]
# We wrap the logic in "sh -c" so Fish doesn't try to parse the Bash syntax.
command = '''
sh -c '
if [ -f package.json ]; then
  ver=$(grep "\"react\":" package.json | head -n1 | sed -E "s/.*: *\"([^\"]*)\".*/\1/" | sed "s/[\^~]//g")
  if [ -n "$ver" ]; then
    echo "on  v$ver"
  fi
fi
'
'''
detect_files = ['package.json']
format = '[$output ](bold blue)'

[custom.typescript]
command = '''
sh -c '
if [ -f package.json ]; then
  ver=$(grep "\"typescript\":" package.json | head -n1 | sed -E "s/.*: *\"([^\"]*)\".*/\1/" | sed "s/[\^~]//g")
  if [ -n "$ver" ]; then
    echo "via  v$ver"
    exit 0
  fi
fi
if ls *.ts *.tsx >/dev/null 2>&1; then
  echo "via  v$(tsc --version | cut -d \" \" -f 2)"
fi
'
'''
detect_files = ['package.json', 'tsconfig.json']
detect_extensions = ['ts', 'tsx']
format = '[$output ](bold blue)'


[custom.nextjs]
command = '''
sh -c '
if [ -f package.json ]; then
  ver=$(grep "\"next\":" package.json | head -n1 | sed -E "s/.*: *\"([^\"]*)\".*/\1/" | sed "s/[\^~]//g")
  if [ -n "$ver" ]; then
    echo "using  v$ver"
  fi
fi
'
'''
detect_files = ['next.config.js', 'next.config.mjs', 'package.json']
format = '[$output ](bold white)'



[custom.tailwind]
command = '''
sh -c '
if [ -f package.json ]; then
  ver=$(grep "\"tailwindcss\":" package.json | head -n1 | sed -E "s/.*: *\"([^\"]*)\".*/\1/" | sed "s/[\^~]//g")
  if [ -n "$ver" ]; then
    echo "with 󱏿 v$ver"
  fi
fi
'
'''
detect_files = ['tailwind.config.js', 'tailwind.config.cjs', 'tailwind.config.mjs', 'tailwind.config.ts','package.json']
format = '[$output ](bold cyan)'
